### ISSUE TITLE
main was red for 96 hours and the check that caught it fired in 3 seconds — the defect is ATTENTION, not detection, and nothing makes a red main visible in the working loop

### ISSUE THREAD

**Issue by ciresnave** [ThinkersJournal/KISS#322]
## The gap

**Nothing makes a red `main` visible to anyone working in this repo.** The signal exists, fires correctly, and has **no consumer**.

## The instance, measured

`traceability.yml`, branch `main`, `event=push`:

```
ee1d186f5  push  success  2026-08-21T17:59:25Z     <- #311 lands, green
d955e7634  push  FAILURE  2026-08-21T18:00:27Z     <- #315 lands, red 3 seconds later
1e800f1e4  push  FAILURE  2026-08-21T18:00:43Z
```

**`main` has been red since 2026-08-21T18:00:27Z. It was found on 2026-08-26T02:01Z — ninety-six hours later — and only because an unrelated PR (#314) inherited the failure and someone read the job log.**

The cause is #321's subject (a semantic merge conflict between #311 and #315). **This issue is not about that break. It is about the ninety-six hours.**

## The defect is ATTENTION, not DETECTION — and that changes which fix is right

**The merge-result check already exists and it worked.** It ran on the right commit and went red within three seconds. The instrument was correct, prompt, and specific.

**So "add a merge queue" is the wrong lesson to draw first.** A merge queue or required status check would *prevent* the bad merge, which is genuinely valuable and worth doing on its own merits — *"both PRs green"* and *"main green"* are different claims, and only the first is ever checked today. **But prevention is not what failed here.** What failed is that **a red default branch produced no consequence for four days.** Adding prevention to a system whose existing detection goes unread buys less than it appears to.

## Why it has no consumer, concretely

**Everyone working in this repo works from `gh pr` output, local tool runs, and `--ratchet`.** None of those look at `main`'s own workflow status:

- `gh pr checks <n>` reports the **PR's** runs, not main's.
- A local `pytest` / lint / `--ratchet` run reports **the working tree**, and a branch cut before the break is green in exactly the way main is not.
- `--ratchet --base-ref origin/main` reads main's **content**, never its **CI state**.

**A red `main` is invisible in the entire working loop.** That is why four days was possible without anyone being careless.

## The second-order cost, which is the one that compounds

**`traceability` on `main` is now a four-day-old always-red.** A gate that has been red long enough stops being read as a gate — the next real failure arrives into a job everyone already expects to be failing.

**This is the same shape as the `strict` job**, which is red **by design** on every PR and correctly ignored. The difference between "red by design" and "red because main is broken" is currently **invisible from the outside**, and that is precisely what makes a genuine red cheap to miss.

## Candidate fixes, not ruled

1. **Make main's health visible where people already look** — the cheapest real fix, since it needs no new discipline.
2. **Branch protection / required checks** — prevention. Worth doing, but on its own merits rather than as this issue's fix.
3. **Distinguish red-by-design from red-by-breakage** so an always-red job cannot camouflage a real one. `strict` being permanently red is the live example of the camouflage.

**No ruling on which; the point of filing is that #321 discharges the instance and leaves the mechanism untouched.**

## Provenance

**The reframing is the portfolio PM's and it corrected me.** I wrote in #321's first body that the break *"exists only in the merge result, and nothing tested that."* **That was false** — they measured the push-triggered runs above and showed detection had worked. #321's body has been corrected.

**The correction makes the finding worse rather than better**, which is why it is worth its own issue: *"the one place this portfolio's instruments did not fail today, and it cost the same as if they had."*

**Comment by ciresnave** [comment]
# Measured at the granularity the claim lives at — and my camouflage claim is mostly WRONG

The portfolio PM measured per-**workflow**, got `traceability: failure, failure, success, success, success`, and **flagged that it tested a different claim rather than reporting it as a clean negative** — since `strict` is a **job**, not a workflow. That flag was right, and settling it was mine because I know which job `strict` is. Settled:

## `strict` is a separate job with `continue-on-error: true`

`.github/workflows/traceability.yml:169`, job-scoped, sitting above the `--strict` step at :180.

**So `strict`'s permanent red is EXCLUDED from the workflow conclusion.** The PM's measurement is not only correct, it is **on point**: at workflow level the conclusion **cleanly tracks the real gates**, and the two `failure`s are exactly the two commits where `kiss-trace` broke.

## And the design already anticipated my concern — the workflow says so, at :161–167

> *"Non-blocking BY DESIGN, and the reason matters: **a gate that can never go green — including for
> the commits that would fix it — gets bypassed by habit, and decays back into a green check that
> means nothing.** So an untested MUST is reported here on every PR, and hard-fails the two
> transitions it actually invalidates (a freeze, and a conformance claim) rather than every commit."*

**That is my always-red decay hazard, identified and solved before I raised it.** Candidate fix 3 above — *"distinguish red-by-design from red-by-breakage"* — **asks for something the design already does at the level that matters.**

## What survives, stated at its real size

**(a) FALSE at workflow level.** No camouflage. `continue-on-error` removes `strict` from the conclusion.

**(b) TRUE but small at PR-check level.** `gh pr checks <n>` does list `strict fail` beside genuine failures. **I hit it myself on #318 earlier tonight** and had to run a comparison against #315 / #311 / #301 to establish that `strict` was baseline rather than mine. **The cost is a lookup, not a miss** — and a lookup is a real cost only when someone is already looking.

**(c) NOT the cause of this incident, and this is the part I should not have blurred.** Nobody looked at main's status **at all**. Offering camouflage as the mechanism was **overreach**: it is a separate, smaller, real hazard that had **no role in the ninety-six hours.**

## What this does NOT change

**The issue's core finding stands untouched**, because it never rested on the camouflage claim: **a red `main` is invisible in the entire working loop** — `gh pr checks` reports the PR's runs, local runs report the working tree, `--base-ref origin/main` reads content and never CI state. **Four instruments, all correct, none of which can see it.** That is the defect, and it is a mechanism rather than a lapse.

**Candidate fix 3 is withdrawn.** 1 and 2 stand.

## Recorded because the shape is this issue's own subject

**A negative result at the wrong granularity is not a disconfirmation** — the PM's discipline in saying so rather than reporting "no always-red found" is what made the real measurement happen. **And the real measurement disconfirmed the person who asked for it**, which is the direction that does not get checked.

**Comment by ciresnave** [comment]
## The prevention half, filed here at the architect's ruling — and it is not a substitute for this issue's subject

**#322's finding is ATTENTION: a red `main` produced no consequence for ninety-six hours.** This is the other half, and the distinction matters because the fixes are different and neither covers the other:

- **Attention** — the merge-result check *existed*, fired in three seconds, and had **no consumer**. That is this issue.
- **Prevention** — ***"both PRs green" and "main green" are different claims, and only the first was ever checked.*** Nothing tested the merge result *before* it became `main`.

**Prevention is not what failed for the ninety-six hours.** It is what failed for the break itself.

### The rule

> **Run the tool suite on the MERGE TREE before merging.**

It is the technique the architect used to clear #300 — compose the branch with `main` in a throwaway worktree and run the instrument on the composed state — promoted from rescue to habit. **It costs no shas and does not disturb a queued PR.**

### It would have caught this one, demonstrated rather than argued

```
ee1d186  GREEN  conform: PROVEN batch 1 (#311)
d955e76  RED    tools: the ratchet's DIMENSION SET is now checked (#315)
            AttributeError: 'tuple' object has no attribute 'get'
```

**Both PRs were green on their own branches. The merge result was red the instant it existed, and was testable in one command at that instant.** Nobody had to wait four days to learn it — the composed state was never run, because nothing asks anyone to run it.

### Mechanizable, which is the part worth insisting on

**A habit decays; a setting does not.** GitHub's **"require branches to be up to date before merging"** *is* this rule enforced — it forces the branch to carry `main`'s head before its checks count, so the run that gates the merge *is* the run on the merge result.

**Verified, not relayed:** `GET /repos/ThinkersJournal/KISS/branches/main/protection` → **404 `Branch not protected`.** There is no protection, no required check, and no merge queue today, so this is available and unused rather than configured-and-bypassed.

### A second instance, in another repo, found within minutes

Baracuda had told the PM that five of their PRs were **safe to merge in any order** — derived from `git merge-tree` being **conflict-free**. That proves **textual** composition only. Three of the five touch the same `ci.yml`, each CI-tested against `main`, **none against the others.**

***"Any order is safe"* is exactly the claim #311×#315 falsifies**, and it was found by someone who was not looking for it, in a different repo, about a different file. The portable form:

> **A signature — or a workflow file, or a floor's dimension set — is a contract with a SET, and nothing enumerates the set.** #271 was a dimension set with no check over the set; this is a **caller** set with no check over the set. Both were green at every point anyone measured.

### What I am not claiming

**This does not make the attention fix optional.** A merge-tree run is a gate someone has to pass; #322's finding is that a gate nobody reads is not a gate. **Prevention plus an unread signal is still an unread signal** — the next semantic conflict that slips a merge-tree run lands in exactly the four-day silence this issue documents.
